
apiVersion: apps/v1
kind: Deployment
metadata:
  name: div-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: div
  template:
    metadata:
      labels:
        app: div
    spec:
      containers:
      - name: div
        image: yourdockerhub/calc-div:v1
        ports:
        - containerPort: 5000
