
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mul-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mul
  template:
    metadata:
      labels:
        app: mul
    spec:
      containers:
      - name: mul
        image: yourdockerhub/calc-mul:v1
        ports:
        - containerPort: 5000
